kind: PersistentVolume
apiVersion: v1
metadata:
  name: elastic-pv-volume
  namespace: kube-logging
  labels:
    type: local
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data/elasticsearch/volume
    server: 172.16.17.37
